import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { connectDB } from "@/lib/db";
import Analysis from "@/models/Analysis";
import User from "@/models/User";
import mongoose from "mongoose";
import { authOptions } from "@/lib/auth";
import { parseRepoUrl, createGitHubIssue } from "@/lib/github";

export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { id } = await params;
    if (!id || !mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: "Invalid analysis ID" }, { status: 400 });
    }

    await connectDB();
    const [analysis, user] = await Promise.all([
      Analysis.findById(id).lean(),
      User.findById(session.user.id).lean(),
    ]);

    if (!analysis) {
      return NextResponse.json({ error: "Analysis not found" }, { status: 404 });
    }
    if (analysis.userId?.toString() !== session.user.id) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
    if (!user?.githubAccessToken) {
      return NextResponse.json(
        { error: "No GitHub token found. Please sign out and sign in again to grant issue creation permissions." },
        { status: 403 }
      );
    }

    const parsed = parseRepoUrl(analysis.repoUrl);
    if (!parsed) {
      return NextResponse.json({ error: "Could not parse repository URL" }, { status: 400 });
    }

    const { owner, repo } = parsed;
    const { aiResult, errorMessage } = analysis;
    const shortSha = aiResult.suspected_commit_sha.slice(0, 7);
    const baseUrl = process.env.NEXTAUTH_URL || "http://localhost:3000";

    const title = `Bug: ${aiResult.suspected_commit_message.slice(0, 80)}`;
    const body = `## Bug Analysis by CommitDetective AI

**Suspected Commit:** [\`${shortSha}\`](https://github.com/${owner}/${repo}/commit/${aiResult.suspected_commit_sha}) — ${aiResult.suspected_commit_message}

### Error Message
\`\`\`
${errorMessage.slice(0, 1000)}${errorMessage.length > 1000 ? "\n... (truncated)" : ""}
\`\`\`

### AI Analysis
${aiResult.reason}

### Suggested Fix
${aiResult.suggested_fix}

---
*Analysis generated by [CommitDetective AI](${baseUrl}/share/${id})*`;

    const issue = await createGitHubIssue(owner, repo, title, body, user.githubAccessToken);

    return NextResponse.json({ issueUrl: issue.url, issueNumber: issue.number });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    console.error("[create-issue]", err);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
